"""empty message

Revision ID: 37806bd3a594
Revises: 58a0624b7adc
Create Date: 2022-05-29 13:52:46.957035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37806bd3a594'
down_revision = '58a0624b7adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
