"""empty message

Revision ID: 96f73dd86415
Revises: b54b0d865ac3
Create Date: 2022-05-31 00:43:56.284491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96f73dd86415'
down_revision = 'b54b0d865ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('book', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('book', 'author',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('book', 'price',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('book', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('book', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('book', 'stock',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('book', 'genre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('book', 'publisher',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('comments', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('book', 'publisher',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('book', 'genre',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('book', 'stock',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('book', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('book', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('book', 'price',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('book', 'author',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('book', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_table('user')
    # ### end Alembic commands ###
