"""empty message

Revision ID: b54b0d865ac3
Revises: 37806bd3a594
Create Date: 2022-05-29 14:20:28.012947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54b0d865ac3'
down_revision = '37806bd3a594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('book_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'book_id')
    # ### end Alembic commands ###
